version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./etc/nginx.conf:/etc/nginx/nginx.conf"
      - "./etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./site:/usr/share/nginx/html"
